---
title: "Interactive graph examples"
author: "Oswaldo Felix"
date: "10/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here, we'll practice creating some interactive graphs and tables using built-in datasets in R packages.

- Interative plots: {plotly}
- Interative tables: {DT}

```{r, include = FALSE}
# Attach packages
library(tidyverse)
library(plotly)
library(DT)
```


### A. Interactive graph of iris dimensions

Using Edgar Anderson's famous 'iris' dataset
```{r, echo = FALSE}
# Create interactive graph
iris_graph <- ggplot(data = iris, 
                     aes(x = Petal.Width, 
                         y = Petal.Length)) +
  geom_point(aes(size = Sepal.Width, 
                 color = Species), 
             alpha = 0.5) +
  theme_minimal() +
  labs(x = "Petal Width [cm]", y = "Petal Length [cm]", title = "My iris graph")

# iris_graph

ggplotly(iris_graph)
```

### Make an interactive table with DT
```{r}
datatable(msleep)
```

